import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

<p className="text-xs text-gray-500 text-center my-6">
  Designed and developed by{" "}
  <a
    href="https://jaya-portfolio-five.vercel.app/"
    target="_blank"
    rel="noopener noreferrer"
    className="text-blue-600 hover:underline font-medium"
  >
    Jaya Kumar
  </a>
</p>

      </body>
    </html>
  );
}
